from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("report/", views.report_incident, name="report_incident"),
    path("reports/", views.my_reports, name="my_reports"),
    path("incidents/<uuid:pk>/", views.incident_detail, name="incident_detail"),
    path("incidents/<uuid:pk>/manage/", views.manage_incident, name="manage_incident"),
    path("evidence/<uuid:pk>/download/", views.evidence_download, name="evidence_download"),
    path("map/", views.city_map, name="city_map"),
    path("map/incidents.geojson", views.public_incidents_geojson, name="public_incidents_geojson"),
    path("map/watch-groups.geojson", views.public_watch_groups_geojson, name="public_watch_groups_geojson"),
    path("around-me/", views.around_me, name="around_me"),
    path("alerts/", views.alerts, name="alerts"),
    path("alerts/new/", views.create_alert, name="create_alert"),
    path("command/", views.command_dashboard, name="command_dashboard"),
    path("command/delivery/", views.delivery_command, name="delivery_command"),
    path("command/delivery/<uuid:pk>/", views.delivery_case_detail, name="delivery_case_detail"),
    path("command/delivery/<uuid:pk>/action/", views.delivery_case_action, name="delivery_case_action"),
    path("command/delivery/<uuid:pk>/handoff/", views.delivery_handoff_request, name="delivery_handoff_request"),
    path("command/handoffs/<int:pk>/respond/", views.delivery_handoff_response, name="delivery_handoff_response"),
    path("command/recommendations/<int:pk>/", views.recommendation_action, name="recommendation_action"),
    path("command/notifications/<int:pk>/read/", views.notification_read, name="notification_read"),
    path("services/", views.service_desks, name="service_desks"),
    path("services/<uuid:pk>/", views.service_case, name="service_case"),
    path("services/<uuid:pk>/message/", views.service_message, name="service_message"),
    path("watch/", views.watch_groups, name="watch_groups"),
    path("watch/new/", views.watch_group_create, name="watch_group_create"),
    path("watch/<uuid:pk>/", views.watch_group_detail, name="watch_group_detail"),
    path("watch/<uuid:pk>/join/", views.watch_group_join, name="watch_group_join"),
    path("watch/<uuid:pk>/leave/", views.watch_group_leave, name="watch_group_leave"),
    path("command/watch-groups/", views.watch_command, name="watch_command"),
    path("command/watch-groups/<uuid:pk>/action/", views.watch_group_action, name="watch_group_action"),
    path("command/watch-memberships/<int:pk>/action/", views.watch_membership_action, name="watch_membership_action"),
    path("emergency/", views.emergency, name="emergency"),
]
