# Generated by Django 5.2.11 on 2026-08-23 17:21

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone_first_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='JPEG, PNG or WebP. Maximum file size: 5 MB.', upload_to='profile_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), accounts.models.validate_profile_photo_size]),
        ),
    ]
