# Generated by Django 5.2.11 on 2026-08-22 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_virtual_public_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodWatchGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=1000)),
                ('centre_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('centre_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius_km', models.DecimalField(decimal_places=1, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('pending', 'Pending police review'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16)),
                ('is_map_visible', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_groups', to='operations.location')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_watch_groups', to=settings.AUTH_USER_MODEL)),
                ('police_organisation', models.ForeignKey(blank=True, limit_choices_to={'kind': 'police'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='watch_groups', to='operations.organisation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='watch_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='operations.neighborhoodwatchgroup'),
        ),
        migrations.CreateModel(
            name='NeighborhoodWatchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('member', 'Member')], default='member', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('left', 'Left group')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='operations.neighborhoodwatchgroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_watch_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='neighborhoodwatchgroup',
            index=models.Index(fields=['status', 'is_map_visible'], name='operations__status_2b38ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='neighborhoodwatchmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_watch_member'),
        ),
    ]
