# Generated by Django 5.2.11 on 2026-08-22 22:02

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_delivery_engine(apps, schema_editor):
    Incident = apps.get_model("operations", "Incident")
    ServiceDeskCase = apps.get_model("operations", "ServiceDeskCase")
    DeliveryCase = apps.get_model("operations", "DeliveryCase")
    OperationalRecommendation = apps.get_model("operations", "OperationalRecommendation")
    incident_slas = {
        "critical": (5, 10, 240), "high": (15, 30, 720),
        "medium": (30, 60, 1440), "low": (60, 240, 4320),
    }
    for incident in Incident.objects.all():
        acknowledgement, assignment, resolution = incident_slas.get(incident.priority, incident_slas["medium"])
        stage = "closed" if incident.status == "closed" else "resolved" if incident.status == "resolved" else "assigned" if incident.assigned_to_id else "open"
        DeliveryCase.objects.create(
            incident_id=incident.pk,
            organisation_id=incident.assigned_organisation_id,
            assigned_to_id=incident.assigned_to_id,
            stage=stage,
            acknowledgement_due_at=incident.created_at + datetime.timedelta(minutes=acknowledgement),
            assignment_due_at=incident.created_at + datetime.timedelta(minutes=assignment),
            resolution_due_at=incident.created_at + datetime.timedelta(minutes=resolution),
            assigned_at=incident.created_at if incident.assigned_to_id else None,
            resolved_at=incident.resolved_at,
        )
    for case in ServiceDeskCase.objects.all():
        stage = "closed" if case.status == "closed" else "resolved" if case.status == "resolved" else "in_progress" if case.status == "in_progress" else "assigned" if case.assigned_to_id else "open"
        DeliveryCase.objects.create(
            service_case_id=case.pk,
            organisation_id=case.assigned_organisation_id,
            assigned_to_id=case.assigned_to_id,
            stage=stage,
            acknowledgement_due_at=case.created_at + datetime.timedelta(minutes=60),
            assignment_due_at=case.created_at + datetime.timedelta(minutes=240),
            resolution_due_at=case.created_at + datetime.timedelta(minutes=2880),
            assigned_at=case.created_at if case.assigned_to_id else None,
        )
    recommendations = (
        ("strategy-survivor-safe-gbv", "survivor_safety", "high", "Establish a survivor-safe GBV and child-protection route", "Use neutral notifications, safe callback windows, specialist access and multi-agency referral without exposing sensitive reports in ordinary queues.", "Botswana Police Service 2024 Annual Report", "https://www.police.gov.bw/images/publications/Annual_Report_final2024.pdf"),
        ("strategy-road-safety-hotspots", "road_safety", "high", "Operationalise road-safety hotspot response", "Combine crash, near-miss, speeding, lighting and road-hazard reports into timed patrol and repair recommendations.", "Statistics Botswana Transport Report 2024", "https://www.statsbots.org.bw/sites/default/files/Transport%20and%20Infrastructure%20Statistics%20Report%202024.pdf"),
        ("strategy-assisted-low-data-access", "digital_access", "medium", "Add assisted and low-bandwidth service channels", "Connect web, USSD, SMS, call-centre and kgotla-assisted access to the same case record so residents do not restart requests.", "SmartBots public-sector transformation", "https://smartbots.gov.bw/node/77"),
        ("strategy-government-service-catalogue", "government_services", "medium", "Maintain a verified government service catalogue", "Publish responsible agencies, requirements, fees, locations and verification dates, with human escalation when guidance is uncertain.", "Botswana ICT Roadmap 2030 update", "https://dailynews.gov.bw/news-detail/90463"),
    )
    now = django.utils.timezone.now()
    for fingerprint, category, priority, title, summary, source_label, source_url in recommendations:
        OperationalRecommendation.objects.get_or_create(
            fingerprint=fingerprint,
            defaults={
                "category": category, "priority": priority, "title": title,
                "summary": summary, "source_label": source_label,
                "source_url": source_url, "last_generated_at": now,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_neighborhoodwatchgroup_incident_watch_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(max_length=1200)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source_label', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], db_index=True, default='proposed', max_length=16)),
                ('last_generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('priority', '-last_generated_at'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('open', 'Awaiting acknowledgement'), ('acknowledged', 'Acknowledged'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('acknowledgement_due_at', models.DateTimeField(db_index=True)),
                ('assignment_due_at', models.DateTimeField(db_index=True)),
                ('resolution_due_at', models.DateTimeField(db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('last_breach', models.CharField(blank=True, max_length=24)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalated_delivery_cases', to='operations.organisation')),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_case', to='operations.incident')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cases', to='operations.organisation')),
                ('service_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_case', to='operations.servicedeskcase')),
            ],
            options={
                'ordering': ('acknowledgement_due_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AuthorityHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(max_length=1000)),
                ('response_note', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('requested', 'Awaiting acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_handoffs', to='operations.organisation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_handoffs', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_handoffs', to=settings.AUTH_USER_MODEL)),
                ('to_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_handoffs', to='operations.organisation')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='operations.deliverycase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.deliverycase')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.organisation')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shifts', to='operations.organisation')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary responder'), ('backup', 'Backup responder'), ('supervisor', 'Shift supervisor')], default='primary', max_length=16)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.dutyshift')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRoutingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('case_type', models.CharField(choices=[('incident', 'Incident report'), ('virtual_service', 'Virtual-service case')], db_index=True, max_length=20)),
                ('incident_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Leave blank to match every priority.', max_length=12)),
                ('service_desk', models.CharField(blank=True, choices=[('police', 'Virtual Police Station'), ('government', 'Government Virtual Assistance'), ('traffic', 'Traffic Police'), ('fire', 'Fire and emergency')], max_length=20)),
                ('service_request_type', models.CharField(blank=True, choices=[('police_assistance', 'Police: non-emergency assistance'), ('police_follow_up', 'Police: case or report follow-up'), ('crime_prevention', 'Police: crime-prevention guidance'), ('government_information', 'Government: service information'), ('application_guidance', 'Government: application guidance'), ('service_referral', 'Government: service referral'), ('traffic_assistance', 'Traffic: non-emergency assistance'), ('fire_safety', 'Fire: safety guidance'), ('other', 'Other assistance')], max_length=32)),
                ('acknowledgement_minutes', models.PositiveIntegerField(default=15)),
                ('assignment_minutes', models.PositiveIntegerField(default=30)),
                ('resolution_minutes', models.PositiveIntegerField(default=1440)),
                ('repeat_escalation_minutes', models.PositiveIntegerField(default=30)),
                ('precedence', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('destination_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_policies', to='operations.organisation')),
                ('escalation_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_policies', to='operations.organisation')),
                ('incident_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_policies', to='operations.incidentcategory')),
            ],
            options={
                'ordering': ('precedence', 'name'),
            },
        ),
        migrations.AddField(
            model_name='deliverycase',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_cases', to='operations.serviceroutingpolicy'),
        ),
        migrations.CreateModel(
            name='AuthorityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('assignment', 'Assignment'), ('sla_breach', 'SLA breach'), ('handoff', 'Authority handoff'), ('recommendation', 'Recommendation')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('body', models.CharField(max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_notifications', to=settings.AUTH_USER_MODEL)),
                ('delivery_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.deliverycase')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='operations__user_id_1cfc7a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dutyshift',
            index=models.Index(fields=['organisation', 'is_active', 'starts_at', 'ends_at'], name='operations__organis_fdc9ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='dutyassignment',
            constraint=models.UniqueConstraint(fields=('shift', 'user'), name='unique_shift_assignment'),
        ),
        migrations.AddIndex(
            model_name='deliverycase',
            index=models.Index(fields=['stage', 'organisation', 'acknowledgement_due_at'], name='operations__stage_fa21c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverycase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('incident__isnull', False), ('service_case__isnull', True)), models.Q(('incident__isnull', True), ('service_case__isnull', False)), _connector='OR'), name='delivery_case_has_one_source'),
        ),
        migrations.RunPython(backfill_delivery_engine, migrations.RunPython.noop),
    ]
