# Generated by Django 5.2.11 on 2026-08-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_service_delivery_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='integration_status',
            field=models.CharField(choices=[('configured', 'Configured internally'), ('onboarding', 'Authority onboarding'), ('connected', 'Authority connected'), ('suspended', 'Integration suspended')], db_index=True, default='configured', max_length=16),
        ),
        migrations.AddField(
            model_name='organisation',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='routes_to',
            field=models.CharField(choices=[('government', 'Government service centre'), ('police', 'Police'), ('traffic', 'Traffic police'), ('fire', 'Fire and rescue'), ('medical', 'Emergency medical services'), ('council', 'City council'), ('water', 'Water authority'), ('electricity', 'Electricity authority'), ('roads', 'Roads authority'), ('disaster', 'Disaster management')], max_length=24),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='kind',
            field=models.CharField(choices=[('government', 'Government service centre'), ('police', 'Police'), ('traffic', 'Traffic police'), ('fire', 'Fire and rescue'), ('medical', 'Emergency medical services'), ('council', 'City council'), ('water', 'Water authority'), ('electricity', 'Electricity authority'), ('roads', 'Roads authority'), ('disaster', 'Disaster management')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
